const path = 'https://ltroller.github.io/beer-db/assets/';

window.beers = [
  {
    name: 'Jever Pils',
    description: 'Friesisch herb!',
    origin: 'Germany',
    preview: `${path}jever.jpg`,
    rating: 4.5,
  },
  {
    name: 'Leffe Blonde',
    description: 'Abbey beer with a full sunny golden color',
    origin: 'Belgium',
    preview: `${path}leffe.jpg`,
    rating: 4.0,
  },
  {
    name: 'Berliner Kindl',
    description: 'The former West Berlin classic Pils',
    origin: 'Germany',
    preview: `${path}berliner-kindl.jpg`,
    rating: 4.0,
  },
  {
    name: 'Anchor Steam',
    description: 'A San Francisco tradition since 1896.',
    origin: 'USA',
    preview: `${path}jever.jpg`,
    rating: 2.5,
  },
  {
    name: 'Berliner Pilsner',
    description: 'The former East Berlin classic Pils',
    origin: 'Germany',
    preview: `${path}berliner-pilsner.jpg`,
    rating: 4.5,
  },
  {
    name: 'Paulaner',
    description: 'The famous hefeweizen from Munich',
    origin: 'Germany',
    preview: `${path}paulaner.jpg`,
    rating: 3.5,
  },
  {
    name: 'Sternburg Export',
    description: "Punk's not dead",
    origin: 'Germany',
    preview: `${path}berliner-kindl.jpg`,
    rating: 3.0,
  },
  {
    name: 'Trumer Pils',
    description: 'Austrian brewing meets Berkeley.',
    origin: 'USA/Austria',
    preview: `${path}trumerpils.jpg`,
    rating: 3.0,
  },
  {
    name: 'Stierbier',
    description: 'Why is this even here?',
    origin: 'Germany',
    preview: `${path}stier-bier.jpg`,
    rating: 3.0,
  },
  {
    name: 'Oettinger',
    description: "Germany's cheapest beer, for a reason.",
    origin: 'Germany',
    preview: `${path}oettinger.jpg`,
    rating: 2.5,
  },
  {
    name: 'Pilsner Urquell',
    description: 'The original, from Pilzen.',
    origin: 'Czech Republic',
    preview: `${path}pilsnerurquell.jpg`,
    rating: 4.5,
  },
  {
    name: 'Kronenbourg: 1664',
    description: 'It will do the job.',
    origin: 'France',
    preview: `${path}kronenbourg.jpg`,
    rating: 3.0,
  },
  {
    name: 'Augustiner Edelstoff',
    description: 'Another classic from Munich',
    origin: 'Germany',
    preview: `${path}edelstoff.jpg`,
    rating: 4.0,
  },
  {
    name: 'Pabst Blue Ribbon',
    description: 'If you can handle the headache, the taste is ok.',
    origin: 'USA',
    preview: `${path}pbr.jpg`,
    rating: 3.0,
  },
  {
    name: 'Bière du Démon',
    description: "There's only one reason to drink this.",
    origin: 'France',
    preview: `${path}pbr.jpg`,
    rating: 1.5,
  },
  {
    name: 'Modelo',
    description: "It's modelo time!",
    origin: 'Mexico',
    preview: `${path}modelo.jpg`,
    rating: 3.0,
  },
  {
    name: "Beck's",
    description: 'In a bind, this will do the trick.',
    origin: 'Germany',
    preview: `${path}becks.jpg`,
    rating: 3.0,
  },
  {
    name: 'Corona',
    description: "How's that name working out for you?",
    origin: 'Mexico',
    preview: `${path}corona.jpg`,
    rating: 3.0,
  },
  {
    name: 'Desperados',
    description:
      'Certainly not beer. Formerly from France, now from Netherlands.',
    origin: 'Netherlands',
    preview: `${path}despe.jpg`,
    rating: 1.0,
  },
  {
    name: 'Heineken',
    description: 'No love lost here.',
    origin: 'Netherlands',
    preview: `${path}corona.jpg`,
    rating: 2.5,
  },
  {
    name: 'Staropramen',
    description: 'Bohemian pleasures.',
    origin: 'Czech Republic',
    preview: `${path}staro.jpg`,
    rating: 3.5,
  },
  {
    name: 'Kozel',
    description: 'This goat sure knows how to brew beer.',
    origin: 'Czech Republic',
    preview: `${path}kozel.jpg`,
    rating: 4.5,
  },
  {
    name: 'Königs Pilsener',
    description: 'KöPi may not be the king, but a decent beer nonetheless.',
    origin: 'Germany',
    preview: `${path}kopi.jpg`,
    rating: 3.5,
  },
  {
    name: 'Radeberger',
    description: 'Dresden is calling, or is it?',
    origin: 'Germany',
    preview: `${path}radeberger.jpg`,
    rating: 2.5,
  },
  {
    name: 'Bud',
    description: 'No... just... no!',
    origin: 'USA',
    preview: `${path}bud.jpg`,
    rating: 0.5,
  },
  {
    name: 'Coors',
    description: 'Sigh..',
    origin: 'USA',
    preview: `${path}coors.jpg`,
    rating: 0.5,
  },
  {
    name: 'Budweiser',
    description: "Now we're talking!",
    origin: 'Czech Republic',
    preview: `${path}budweiser.jpg`,
    rating: 4.5,
  },
];
